openapi: 3.0.0
info:
  title: Healthcare Appointment Booking API
  version: 1.0.0
paths:
  /appointments:
    post:
      summary: Create an appointment
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                doctorId:
                  type: string
                dateTime:
                  type: string
                  format: date-time
      responses:
        '201':
          description: Appointment created
        '400':
          description: Time slot not available
  /appointments/{id}/approve:
    put:
      summary: Approve an appointment
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Appointment ID
          schema:
            type: string
      responses:
        '200':
          description: Appointment approved
        '403':
          description: Admin access required
